### ISSUE TITLE
Option to set a font

### ISSUE THREAD

**Issue by sennewood** [lifelike/hexmapextension#12]
It is only needed for the coordinates, but it would be nice to choose a font for the creation. Otherwise every single field have to be touched by hand.

**Comment by lifelike** [comment]
Select the coordinate layer, press ctrl-a to select everything, press ctrl-shift-t to bring up the text properties dialog. It would be very difficult to make some good way to specify the font without reproducing all of that text dialog? A text entry field to paste the text style attribute? Would work, but a bit geeky, and you typically do not have to do this more than once for every game you want to make, so I think it makes more sense to do it manually. There used to be fields for setting the font size and position, but it was pretty pointless I thought since I ended up manually adjusting things every time anyway (also things like text color, drop shadow, everything else you might want to have).
