### ISSUE TITLE
Big center dots

### ISSUE THREAD

**Issue by sennewood** [lifelike/hexmapextension#14]
I created hex grid with 5mm, but the center dots are a little to big:
![hexdots](https://user-images.githubusercontent.com/406414/46037174-b925e380-c107-11e8-8048-a261c02e0427.png)

Maybe use the stroke size for the dot size?

**Comment by lifelike** [comment]
The circle radii are based on stroke-width (CENTERDOT_SIZE_FACTOR = 1.1690625). At least that is the theory. It looks as if they might be a bit bigger than that really. Maybe the circles also have a stroke added around them, so that the total diameter is more than four times the stroke-width? That looks like what is seen in that image.
