### ISSUE TITLE
Measure Hex Size Face-to-Face Like Everyone Else Does!

### ISSUE THREAD

**Issue by tworthington** [lifelike/hexmapextension#44]
I'm amazed.

This is literally, in 45 years of gaming, only the second time I've seen "hex size" mean the point-to-point size.

At the very least, add a prominent note to the documentation on how to convert the normal size of a hex to the size used by the extension.

**Comment by lifelike** [comment]
I agree. I do not think I was aware of that at the time I introduced the option to set a size and then never thought of it more. I tend to experiment until I get the right size (right number of columns and rows in the area I want to cover) instead of focusing on the exact size, and no one else complained. But I think it is better as you say to always measure between the flat sides, as I now know that that is what most expect.
