### ISSUE TITLE
Broken corners when hexagons are very small

### ISSUE THREAD

**Issue by sennewood** [lifelike/hexmapextension#5]
The document has a size of DIN A1 and I let create 600 hexagons in columns:

![tinycorners](https://user-images.githubusercontent.com/406414/34460455-56675eca-ee0f-11e7-8003-f215f2c112bd.png)

**Comment by lifelike** [comment]
Perhaps scale line width by hex size and make the lines slightly longer, but I do not think when scaled up like that it will ever look perfect with disconnected lines. Or is there a way to have 60 degrees pointy ends on the lines? 90 might be an improvement, but not perfect.

**Comment by lifelike** [comment]
Perhaps scale line width by hex size and make the lines slightly longer, but I do not think when scaled up like that it will ever look perfect with disconnected lines. Or is there a way to have 60 degrees pointy ends on the lines? 90 might be an improvement, but not perfect.

Or make each line into multiple line segments, probably 5, but that would have to be optional because of the increase in gris size.

**Comment by lifelike** [comment]
Easier to make each line a 6-sided polygon, but might be very heavy to render and not as convenient to edit when you want to manually do something to hex sides. Could make that an option for when you really want the lines to connect perfectly?

**Comment by sennewood** [comment]
Since someone has to render the grid only once, render time should not be a problem. For my current project I only need to replace the filling in a second step (I'm creating a fantasy map with a tileset). The only thing I do with the hex sides is to make them thinner.

**Comment by lifelike** [comment]
I meant rendering as in when inkscape has to render the drawing to the screen, not only when it exports.

One (crazy?) idea is to still have lines for hex-sides, but give each line a clip-polygon that clips the ends to the correct shape. That will probably be extremely slow when you have a big grid though, but worth trying. If it is too slow it could be made an option for when it really matters.

**Comment by lifelike** [comment]
Or have the option to not use the workaround at all, for all lines, or only for the lines around the edges where it is the most obvious (but the interior lines can be problematic if you make them slightly transparent since now the lines overlap at the vertices, so for the highest quality grid every line would have to be clipped properly).

**Comment by sennewood** [comment]
The rendering for normal sized grids should still be fast.

Only a few people (like me) want to create huge hexmaps and I'm totally fine to wait for better/best results.
