### ISSUE TITLE
Grid layer: combine paths

### ISSUE THREAD

**Issue by sennewood** [lifelike/hexmapextension#8]
The grid layer consists of many single lines. If there isn't a reason against it, the extension could use Inkscapes method to combine all these lines to one single path.

Manually via: _Menu -> Path -> Combine_

**Comment by lifelike** [comment]
It is by design to make it possible to select individual sides to modify or copy or delete.

I can't see any benefit of having them in a single path, but if you want that you can just select that layer and click ctrl-a to select all and combine them. If that makes Inkscape use less memory and/or work faster I guess this would be interesting as an option for when you really do not want a grid that is easy to work with and are content to just have one big path.

The extension can unfortunately not use any of inkscape's methods. It has to create its own SVG. So it would be possible to add this as an option and instead of separate lines create one big path, but it would be a bit of work. Best case it would just be rewriting a few lines though.

**Comment by sennewood** [comment]
You don't have to, I'm fine doing this manually ^^
